-- Based on AmitGolden's dotfiles
require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.autopairs")
require("user.catppuccin")
require("user.cmp")
require("user.dashboard")
require("user.diffview")
require("user.formatter")
require("user.gitsigns")
require("user.lsp")
require("user.lualine")
require("user.nvim-tree")
require("user.presence")
require("user.sort")
require("user.telescope")
require("user.treesitter")
