# animation_duration_ms 250

corner_radius 14
smart_corner_radius on

blur enable
blur_xray disable
blur_passes 2
blur_radius 2

shadows enable
shadows_on_csd disable
shadow_blur_radius 30
shadow_color #000000ff ex, #0000007F

layer_effects "wamBar" blur enable; blur_ignore_transparent true;
layer_effects "wam-shellScratchpad" blur enable; blur_ignore_transparent true;

layer_effects "bar" blur enable; blur_ignore_transparent true;
layer_effects "rofi" blur enable; corner_radius 0; shadows enable; corner_radius 14;

